//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_csvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dblDanhSachMuon
    {
        public int id_danh_sach_muon { get; set; }
        public int id_cbvc { get; set; }
        public Nullable<int> id_phong_su_dung { get; set; }
        public int id_thiet_bi { get; set; }
        public int id_don_vi_tinh { get; set; }
        public int so_luong_muon { get; set; }
        public string yeu_cau { get; set; }
        public Nullable<int> ngay_muon { get; set; }
        public Nullable<int> ngay_tra { get; set; }
    
        public virtual dblCBVC dblCBVC { get; set; }
        public virtual dblDonViTinh dblDonViTinh { get; set; }
        public virtual dblPhongHoc dblPhongHoc { get; set; }
        public virtual dblThietBi dblThietBi { get; set; }
    }
}
