//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_csvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon_an
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mon_an()
        {
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
            this.hoa_don_ban_hang = new HashSet<hoa_don_ban_hang>();
        }
    
        public int id_mon_an { get; set; }
        public string ten_mon_an { get; set; }
        public Nullable<int> id_group_loai_mon_an { get; set; }
        public Nullable<double> price { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual group_loai_mon_an group_loai_mon_an { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don_ban_hang> hoa_don_ban_hang { get; set; }
    }
}
